export const GAME_CONFIG = {
  title: 'Ashen Oath',
  pass: 9,
  renderer: {
    maxPixelRatio: 1.65,
    shadowMapSize: 2048,
    exposure: 0.92,
  },
  camera: {
    fov: 48,
    sprintFov: 53,
    lockFov: 50,
    near: 0.08,
    far: 360,
    yaw: 0,
    pitch: 0.36,
    distance: 7.4,
    minDistance: 3.1,
    maxDistance: 11.5,
    targetHeight: 0.58,
    shoulderOffset: 0.52,
    lookAheadSeconds: 0.14,
    maxLookAhead: 1.15,
    positionSharpness: 15,
    targetSharpness: 20,
    collisionInSharpness: 28,
    collisionOutSharpness: 9,
    collisionPadding: 0.34,
    collisionMinDistance: 0.82,
    mouseSensitivity: 0.00245,
    dragSensitivity: 0.004,
    gamepadLookSpeed: 2.35,
    zoomSensitivity: 0.006,
    lockYawSharpness: 7.5,
    lockTargetWeight: 0.23,
    lockMaxDistance: 19,
  },
  physics: {
    gravity: -26,
    fixedStep: 1 / 60,
    maxSubSteps: 5,
  },
  player: {
    spawn: [0, 1.12, 22] as const,
    capsuleRadius: 0.46,
    capsuleHalfHeight: 0.62,
    controllerOffset: 0.055,
    walkSpeed: 3.7,
    runSpeed: 6.65,
    groundAcceleration: 23,
    sprintAcceleration: 17,
    reversalAcceleration: 29,
    groundDeceleration: 31,
    airAcceleration: 5.5,
    turnSpeedWalk: 9.5,
    turnSpeedRun: 7.4,
    lockTurnSpeed: 13,
    maxFallSpeed: -30,
    groundedPull: -2.8,
    maxStepHeight: 0.38,
    minStepWidth: 0.24,
    snapToGroundDistance: 0.3,
    maxSlopeAngleDegrees: 46,
    slideSlopeAngleDegrees: 52,
    maxHealth: 160,
    maxStamina: 100,
    staminaRegenPerSecond: 34,
    staminaRegenDelay: 0.72,
    sprintStaminaPerSecond: 15,
    dodgeCost: 26,
    dodgeDuration: 0.58,
    dodgeInvulnerableStart: 0.1,
    dodgeInvulnerableEnd: 0.39,
    dodgeDistance: 4.35,
    staggerDuration: 0.52,
    executionDuration: 1.42,
    executionImpactTime: 0.72,
    executionRange: 2.35,
    heavyChargeMin: 0.18,
    heavyChargeMax: 1.05,
    heavyChargeStaminaBase: 29,
    heavyChargeStaminaBonus: 12,
    guardMoveSpeed: 1.65,
    guardDamageLeak: 0.08,
    guardStaminaMultiplier: 1.05,
    parryCost: 14,
    parryDuration: 0.64,
    parryWindowStart: 0.1,
    parryWindowEnd: 0.235,
    healDuration: 1.48,
    healImpactTime: 0.84,
    healAmount: 74,
    flaskCapacity: 3,
    respawnDelay: 2.65,
  },
  combat: {
    lockSearchAngleCos: -0.18,
    hitHeightTolerance: 1.8,
    attacks: {
      light1: {
        duration: 0.61,
        activeStart: 0.21,
        activeEnd: 0.31,
        comboOpen: 0.36,
        staminaCost: 17,
        damage: 28,
        poiseDamage: 24,
        range: 2.25,
        arcCos: 0.08,
        rootDistance: 0.62,
      },
      light2: {
        duration: 0.7,
        activeStart: 0.25,
        activeEnd: 0.38,
        comboOpen: 0.43,
        staminaCost: 19,
        damage: 34,
        poiseDamage: 30,
        range: 2.38,
        arcCos: -0.02,
        rootDistance: 0.74,
      },
      light3: {
        duration: 0.84,
        activeStart: 0.31,
        activeEnd: 0.46,
        comboOpen: 2,
        staminaCost: 23,
        damage: 43,
        poiseDamage: 44,
        range: 2.62,
        arcCos: 0.1,
        rootDistance: 1.02,
      },
      heavy: {
        duration: 1.14,
        activeStart: 0.55,
        activeEnd: 0.7,
        comboOpen: 2,
        staminaCost: 29,
        damage: 52,
        poiseDamage: 58,
        range: 2.65,
        arcCos: 0.22,
        rootDistance: 0.92,
      },
    },
    executionDamage: 999,
    attackTrackingDegrees: 38,
  },
  world: {
    seed: 80717,
    ashCount: 880,
    recoveryRadius: 1.55,
    interactionRadius: 2.35,
    threatRadius: 8.5,
    bossTriggerZ: -90.2,
    widowTriggerZ: -136.0,
    oathkeeperTriggerZ: -190.0,
  },
} as const;
