export const GAME_CONFIG = {
  title: 'Ashen Oath',
  pass: 1,
  renderer: {
    maxPixelRatio: 1.65,
    shadowMapSize: 2048,
    exposure: 0.92,
  },
  camera: {
    fov: 48,
    sprintFov: 53,
    near: 0.08,
    far: 360,
    yaw: 0,
    pitch: 0.36,
    distance: 7.4,
    minDistance: 3.1,
    maxDistance: 11.5,
    targetHeight: 0.58,
    shoulderOffset: 0.52,
    lookAheadSeconds: 0.14,
    maxLookAhead: 1.15,
    positionSharpness: 15,
    targetSharpness: 20,
    collisionInSharpness: 28,
    collisionOutSharpness: 9,
    collisionPadding: 0.34,
    collisionMinDistance: 0.82,
    mouseSensitivity: 0.00245,
    dragSensitivity: 0.004,
    gamepadLookSpeed: 2.35,
    zoomSensitivity: 0.006,
  },
  physics: {
    gravity: -26,
    fixedStep: 1 / 60,
    maxSubSteps: 5,
  },
  player: {
    spawn: [0, 1.12, 22] as const,
    capsuleRadius: 0.46,
    capsuleHalfHeight: 0.62,
    controllerOffset: 0.055,
    walkSpeed: 3.7,
    runSpeed: 6.65,
    groundAcceleration: 23,
    sprintAcceleration: 17,
    reversalAcceleration: 29,
    groundDeceleration: 31,
    airAcceleration: 5.5,
    turnSpeedWalk: 9.5,
    turnSpeedRun: 7.4,
    maxFallSpeed: -30,
    groundedPull: -2.8,
    maxStepHeight: 0.38,
    minStepWidth: 0.24,
    snapToGroundDistance: 0.3,
    maxSlopeAngleDegrees: 46,
    slideSlopeAngleDegrees: 52,
  },
  world: {
    seed: 80717,
    ashCount: 720,
  },
} as const;
