export const GAME_CONFIG = {
  title: 'Ashen Oath',
  pass: 1,
  renderer: {
    maxPixelRatio: 1.75,
    shadowMapSize: 2048,
  },
  camera: {
    fov: 50,
    near: 0.08,
    far: 280,
    yaw: 0,
    pitch: 0.42,
    distance: 8.6,
    minDistance: 3.2,
    maxDistance: 13.5,
    targetHeight: 0.62,
    positionSharpness: 13,
    targetSharpness: 18,
    collisionPadding: 0.38,
    collisionMinDistance: 0.9,
    orbitSensitivity: 0.0042,
    zoomSensitivity: 0.008,
  },
  physics: {
    gravity: -24,
    fixedStep: 1 / 60,
  },
  player: {
    spawn: [0, 1.16, 10] as const,
    capsuleRadius: 0.48,
    capsuleHalfHeight: 0.62,
    controllerOffset: 0.06,
    walkSpeed: 4.25,
    runSpeed: 7.15,
    groundAcceleration: 25,
    groundDeceleration: 32,
    airAcceleration: 7,
    turnSharpness: 16,
    maxFallSpeed: -28,
    groundedPull: -2.4,
    maxStepHeight: 0.42,
    minStepWidth: 0.22,
    snapToGroundDistance: 0.32,
    maxSlopeAngleDegrees: 48,
    slideSlopeAngleDegrees: 54,
  },
} as const;
